credentials:
  usernames:
    user1:
      name: User One
      password: hashed_password_1
  names:
    user1: User One
cookie:
  name: some_cookie_name
  key: some_cookie_key
  expiry_days: 30
preauthorized:
  emails:
    - user1@example.com
mongodb:
  uri: "mongodb+srv://celestino127:C0mpa$$i0n127@cluster0.mongodb.net/myDatabase?retryWrites=true&w=majority"

