credentials:
  usernames:
    jsmith:
      email: celestine.kariuki@strathmore.edu
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Celestine Kariuki 
      password: abc # Will be hashed automatically
    rbriggs:
      email: examiner127@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Mister Examiner 
      password: youpass # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - kcelestinomaria127@gmail.com